// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/integrations/google-calendar": {
    params: {};
  };
  "/portfolio/jupiter-fast-finance": {
    params: {};
  };
  "/portfolio/dr-dipti-ganatra": {
    params: {};
  };
  "/services/seo-optimization": {
    params: {};
  };
  "/services/web-applications": {
    params: {};
  };
  "/portfolio/corporate-zone": {
    params: {};
  };
  "/websites-for-consultants": {
    params: {};
  };
  "/websites-for-real-estate": {
    params: {};
  };
  "/websites-for-restaurants": {
    params: {};
  };
  "/website-cost-calculator": {
    params: {};
  };
  "/websites-for-startups": {
    params: {};
  };
  "/api/booking-settings": {
    params: {};
  };
  "/location/lower-parel": {
    params: {};
  };
  "/location/mahalakshmi": {
    params: {};
  };
  "/location/peddar-road": {
    params: {};
  };
  "/location/pedder-road": {
    params: {};
  };
  "/terms-and-conditions": {
    params: {};
  };
  "/websites-for-doctors": {
    params: {};
  };
  "/websites-for-finance": {
    params: {};
  };
  "/websites-for-lawyers": {
    params: {};
  };
  "/services/google-ads": {
    params: {};
  };
  "/location/ghatkopar": {
    params: {};
  };
  "/lp/thank-you-audit": {
    params: {};
  };
  "/lp/thank-you-quote": {
    params: {};
  };
  "/services/ecommerce": {
    params: {};
  };
  "/location/vikhroli": {
    params: {};
  };
  "/services/meta-ads": {
    params: {};
  };
  "/location/andheri": {
    params: {};
  };
  "/location/bhandup": {
    params: {};
  };
  "/admin/dashboard": {
    params: {};
  };
  "/location/bandra": {
    params: {};
  };
  "/location/mulund": {
    params: {};
  };
  "/admin/blog/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/blog/new": {
    params: {};
  };
  "/location/dadar": {
    params: {};
  };
  "/location/kurla": {
    params: {};
  };
  "/location/nahur": {
    params: {};
  };
  "/location/powai": {
    params: {};
  };
  "/location/thane": {
    params: {};
  };
  "/privacy-policy": {
    params: {};
  };
  "/lp/web-design": {
    params: {};
  };
  "/refund-policy": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/ads-contact": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/book-a-call": {
    params: {};
  };
  "/our-process": {
    params: {};
  };
  "/api/quotes": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/contact-us": {
    params: {};
  };
  "/free-audit": {
    params: {};
  };
  "/thank-you": {
    params: {};
  };
  "/pricing": {
    params: {};
  };
  "/why-us": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/quote": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/integrations/google-calendar" | "/portfolio/jupiter-fast-finance" | "/portfolio/dr-dipti-ganatra" | "/services/seo-optimization" | "/services/web-applications" | "/portfolio/corporate-zone" | "/websites-for-consultants" | "/websites-for-real-estate" | "/websites-for-restaurants" | "/website-cost-calculator" | "/websites-for-startups" | "/api/booking-settings" | "/location/lower-parel" | "/location/mahalakshmi" | "/location/peddar-road" | "/location/pedder-road" | "/terms-and-conditions" | "/websites-for-doctors" | "/websites-for-finance" | "/websites-for-lawyers" | "/services/google-ads" | "/location/ghatkopar" | "/lp/thank-you-audit" | "/lp/thank-you-quote" | "/services/ecommerce" | "/location/vikhroli" | "/services/meta-ads" | "/location/andheri" | "/location/bhandup" | "/admin/dashboard" | "/location/bandra" | "/location/mulund" | "/admin/blog/:id" | "/admin/blog/new" | "/location/dadar" | "/location/kurla" | "/location/nahur" | "/location/powai" | "/location/thane" | "/privacy-policy" | "/lp/web-design" | "/refund-policy" | "/sitemap.xml" | "/admin" | "/ads-contact" | "/blog" | "/book-a-call" | "/our-process" | "/api/quotes" | "/blog/:slug" | "/contact-us" | "/free-audit" | "/thank-you" | "/pricing" | "/why-us" | "/about" | "/quote" | "/*";
  };
  "routes/api.integrations.google-calendar.ts": {
    id: "routes/api.integrations.google-calendar";
    page: "/api/integrations/google-calendar";
  };
  "routes/portfolio.jupiter-fast-finance.tsx": {
    id: "routes/portfolio.jupiter-fast-finance";
    page: "/portfolio/jupiter-fast-finance";
  };
  "routes/portfolio.dr-dipti-ganatra.tsx": {
    id: "routes/portfolio.dr-dipti-ganatra";
    page: "/portfolio/dr-dipti-ganatra";
  };
  "routes/services.seo-optimization.tsx": {
    id: "routes/services.seo-optimization";
    page: "/services/seo-optimization";
  };
  "routes/services.web-applications.tsx": {
    id: "routes/services.web-applications";
    page: "/services/web-applications";
  };
  "routes/portfolio.corporate-zone.tsx": {
    id: "routes/portfolio.corporate-zone";
    page: "/portfolio/corporate-zone";
  };
  "routes/websites-for-consultants.tsx": {
    id: "routes/websites-for-consultants";
    page: "/websites-for-consultants";
  };
  "routes/websites-for-real-estate.tsx": {
    id: "routes/websites-for-real-estate";
    page: "/websites-for-real-estate";
  };
  "routes/websites-for-restaurants.tsx": {
    id: "routes/websites-for-restaurants";
    page: "/websites-for-restaurants";
  };
  "routes/website-cost-calculator.tsx": {
    id: "routes/website-cost-calculator";
    page: "/website-cost-calculator";
  };
  "routes/websites-for-startups.tsx": {
    id: "routes/websites-for-startups";
    page: "/websites-for-startups";
  };
  "routes/api.booking-settings.ts": {
    id: "routes/api.booking-settings";
    page: "/api/booking-settings";
  };
  "routes/location.lower-parel.tsx": {
    id: "routes/location.lower-parel";
    page: "/location/lower-parel";
  };
  "routes/location.mahalakshmi.tsx": {
    id: "routes/location.mahalakshmi";
    page: "/location/mahalakshmi";
  };
  "routes/location.peddar-road.tsx": {
    id: "routes/location.peddar-road";
    page: "/location/peddar-road";
  };
  "routes/location.pedder-road.tsx": {
    id: "routes/location.pedder-road";
    page: "/location/pedder-road";
  };
  "routes/terms-and-conditions.tsx": {
    id: "routes/terms-and-conditions";
    page: "/terms-and-conditions";
  };
  "routes/websites-for-doctors.tsx": {
    id: "routes/websites-for-doctors";
    page: "/websites-for-doctors";
  };
  "routes/websites-for-finance.tsx": {
    id: "routes/websites-for-finance";
    page: "/websites-for-finance";
  };
  "routes/websites-for-lawyers.tsx": {
    id: "routes/websites-for-lawyers";
    page: "/websites-for-lawyers";
  };
  "routes/services.google-ads.tsx": {
    id: "routes/services.google-ads";
    page: "/services/google-ads";
  };
  "routes/location.ghatkopar.tsx": {
    id: "routes/location.ghatkopar";
    page: "/location/ghatkopar";
  };
  "routes/lp.thank-you-audit.tsx": {
    id: "routes/lp.thank-you-audit";
    page: "/lp/thank-you-audit";
  };
  "routes/lp.thank-you-quote.tsx": {
    id: "routes/lp.thank-you-quote";
    page: "/lp/thank-you-quote";
  };
  "routes/services.ecommerce.tsx": {
    id: "routes/services.ecommerce";
    page: "/services/ecommerce";
  };
  "routes/location.vikhroli.tsx": {
    id: "routes/location.vikhroli";
    page: "/location/vikhroli";
  };
  "routes/services.meta-ads.tsx": {
    id: "routes/services.meta-ads";
    page: "/services/meta-ads";
  };
  "routes/location.andheri.tsx": {
    id: "routes/location.andheri";
    page: "/location/andheri";
  };
  "routes/location.bhandup.tsx": {
    id: "routes/location.bhandup";
    page: "/location/bhandup";
  };
  "routes/admin.dashboard.tsx": {
    id: "routes/admin.dashboard";
    page: "/admin/dashboard";
  };
  "routes/location.bandra.tsx": {
    id: "routes/location.bandra";
    page: "/location/bandra";
  };
  "routes/location.mulund.tsx": {
    id: "routes/location.mulund";
    page: "/location/mulund";
  };
  "routes/admin.blog.$id.tsx": {
    id: "routes/admin.blog.$id";
    page: "/admin/blog/:id";
  };
  "routes/admin.blog.new.tsx": {
    id: "routes/admin.blog.new";
    page: "/admin/blog/new";
  };
  "routes/location.dadar.tsx": {
    id: "routes/location.dadar";
    page: "/location/dadar";
  };
  "routes/location.kurla.tsx": {
    id: "routes/location.kurla";
    page: "/location/kurla";
  };
  "routes/location.nahur.tsx": {
    id: "routes/location.nahur";
    page: "/location/nahur";
  };
  "routes/location.powai.tsx": {
    id: "routes/location.powai";
    page: "/location/powai";
  };
  "routes/location.thane.tsx": {
    id: "routes/location.thane";
    page: "/location/thane";
  };
  "routes/privacy-policy.tsx": {
    id: "routes/privacy-policy";
    page: "/privacy-policy";
  };
  "routes/lp.web-design.tsx": {
    id: "routes/lp.web-design";
    page: "/lp/web-design";
  };
  "routes/refund-policy.tsx": {
    id: "routes/refund-policy";
    page: "/refund-policy";
  };
  "routes/sitemap[.]xml.tsx": {
    id: "routes/sitemap[.]xml";
    page: "/sitemap.xml";
  };
  "routes/admin._index.tsx": {
    id: "routes/admin._index";
    page: "/admin";
  };
  "routes/ads-contact.tsx": {
    id: "routes/ads-contact";
    page: "/ads-contact";
  };
  "routes/blog._index.tsx": {
    id: "routes/blog._index";
    page: "/blog";
  };
  "routes/book-a-call.tsx": {
    id: "routes/book-a-call";
    page: "/book-a-call";
  };
  "routes/our-process.tsx": {
    id: "routes/our-process";
    page: "/our-process";
  };
  "routes/api.quotes.ts": {
    id: "routes/api.quotes";
    page: "/api/quotes";
  };
  "routes/blog.$slug.tsx": {
    id: "routes/blog.$slug";
    page: "/blog/:slug";
  };
  "routes/contact-us.tsx": {
    id: "routes/contact-us";
    page: "/contact-us";
  };
  "routes/free-audit.tsx": {
    id: "routes/free-audit";
    page: "/free-audit";
  };
  "routes/thank-you.tsx": {
    id: "routes/thank-you";
    page: "/thank-you";
  };
  "routes/pricing.tsx": {
    id: "routes/pricing";
    page: "/pricing";
  };
  "routes/why-us.tsx": {
    id: "routes/why-us";
    page: "/why-us";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/quote.tsx": {
    id: "routes/quote";
    page: "/quote";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/api.integrations.google-calendar": typeof import("./app/routes/api.integrations.google-calendar.ts");
  "routes/portfolio.jupiter-fast-finance": typeof import("./app/routes/portfolio.jupiter-fast-finance.tsx");
  "routes/portfolio.dr-dipti-ganatra": typeof import("./app/routes/portfolio.dr-dipti-ganatra.tsx");
  "routes/services.seo-optimization": typeof import("./app/routes/services.seo-optimization.tsx");
  "routes/services.web-applications": typeof import("./app/routes/services.web-applications.tsx");
  "routes/portfolio.corporate-zone": typeof import("./app/routes/portfolio.corporate-zone.tsx");
  "routes/websites-for-consultants": typeof import("./app/routes/websites-for-consultants.tsx");
  "routes/websites-for-real-estate": typeof import("./app/routes/websites-for-real-estate.tsx");
  "routes/websites-for-restaurants": typeof import("./app/routes/websites-for-restaurants.tsx");
  "routes/website-cost-calculator": typeof import("./app/routes/website-cost-calculator.tsx");
  "routes/websites-for-startups": typeof import("./app/routes/websites-for-startups.tsx");
  "routes/api.booking-settings": typeof import("./app/routes/api.booking-settings.ts");
  "routes/location.lower-parel": typeof import("./app/routes/location.lower-parel.tsx");
  "routes/location.mahalakshmi": typeof import("./app/routes/location.mahalakshmi.tsx");
  "routes/location.peddar-road": typeof import("./app/routes/location.peddar-road.tsx");
  "routes/location.pedder-road": typeof import("./app/routes/location.pedder-road.tsx");
  "routes/terms-and-conditions": typeof import("./app/routes/terms-and-conditions.tsx");
  "routes/websites-for-doctors": typeof import("./app/routes/websites-for-doctors.tsx");
  "routes/websites-for-finance": typeof import("./app/routes/websites-for-finance.tsx");
  "routes/websites-for-lawyers": typeof import("./app/routes/websites-for-lawyers.tsx");
  "routes/services.google-ads": typeof import("./app/routes/services.google-ads.tsx");
  "routes/location.ghatkopar": typeof import("./app/routes/location.ghatkopar.tsx");
  "routes/lp.thank-you-audit": typeof import("./app/routes/lp.thank-you-audit.tsx");
  "routes/lp.thank-you-quote": typeof import("./app/routes/lp.thank-you-quote.tsx");
  "routes/services.ecommerce": typeof import("./app/routes/services.ecommerce.tsx");
  "routes/location.vikhroli": typeof import("./app/routes/location.vikhroli.tsx");
  "routes/services.meta-ads": typeof import("./app/routes/services.meta-ads.tsx");
  "routes/location.andheri": typeof import("./app/routes/location.andheri.tsx");
  "routes/location.bhandup": typeof import("./app/routes/location.bhandup.tsx");
  "routes/admin.dashboard": typeof import("./app/routes/admin.dashboard.tsx");
  "routes/location.bandra": typeof import("./app/routes/location.bandra.tsx");
  "routes/location.mulund": typeof import("./app/routes/location.mulund.tsx");
  "routes/admin.blog.$id": typeof import("./app/routes/admin.blog.$id.tsx");
  "routes/admin.blog.new": typeof import("./app/routes/admin.blog.new.tsx");
  "routes/location.dadar": typeof import("./app/routes/location.dadar.tsx");
  "routes/location.kurla": typeof import("./app/routes/location.kurla.tsx");
  "routes/location.nahur": typeof import("./app/routes/location.nahur.tsx");
  "routes/location.powai": typeof import("./app/routes/location.powai.tsx");
  "routes/location.thane": typeof import("./app/routes/location.thane.tsx");
  "routes/privacy-policy": typeof import("./app/routes/privacy-policy.tsx");
  "routes/lp.web-design": typeof import("./app/routes/lp.web-design.tsx");
  "routes/refund-policy": typeof import("./app/routes/refund-policy.tsx");
  "routes/sitemap[.]xml": typeof import("./app/routes/sitemap[.]xml.tsx");
  "routes/admin._index": typeof import("./app/routes/admin._index.tsx");
  "routes/ads-contact": typeof import("./app/routes/ads-contact.tsx");
  "routes/blog._index": typeof import("./app/routes/blog._index.tsx");
  "routes/book-a-call": typeof import("./app/routes/book-a-call.tsx");
  "routes/our-process": typeof import("./app/routes/our-process.tsx");
  "routes/api.quotes": typeof import("./app/routes/api.quotes.ts");
  "routes/blog.$slug": typeof import("./app/routes/blog.$slug.tsx");
  "routes/contact-us": typeof import("./app/routes/contact-us.tsx");
  "routes/free-audit": typeof import("./app/routes/free-audit.tsx");
  "routes/thank-you": typeof import("./app/routes/thank-you.tsx");
  "routes/pricing": typeof import("./app/routes/pricing.tsx");
  "routes/why-us": typeof import("./app/routes/why-us.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/quote": typeof import("./app/routes/quote.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};